name: Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  npm-publish:
    name: Publish to npmjs.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish to npmjs.com
        run: .github/scripts/npm-publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # deploy-to-smithery: # TODO: Implement this when the Smithery API supports this
  #   name: Deploy to Smithery
  #   runs-on: ubuntu-latest
  #   needs: npm-publish
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Deploy to Smithery
  #       run: .github/scripts/deploy-to-smithery.sh
  #       env:
  #         SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
