name: PR Checks

on:
  pull_request:
    branches:
      - main

env:
  UPSTREAM_BRANCH: origin/${{ github.base_ref }}

concurrency:
  group: pr-${{ github.event.pull_request.number }}-checks
  cancel-in-progress: true

jobs:
  check-changeset:
    name: Check for changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base branch
        run: git fetch origin main:refs/remotes/origin/main
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check for changeset
        run: npx @changesets/cli status --since=origin/main

  validate-package-version:
    name: Validate package version
    runs-on: ['ubuntu-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run validation script
        run: .github/scripts/validate-package-version.sh
  
  update-mcp-version:
    name: Update MCP version
    runs-on: ['ubuntu-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run validation script
        run: .github/scripts/update-mcp-version.sh
        env:
          PATH_TO_FILE: 'index.js'

  validate-build:
    name: Validate build
    runs-on: ['ubuntu-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Run validation script
        run: .github/scripts/validate-build.sh
